### ISSUE TITLE
Issue 1: Users can add an entry

### ISSUE THREAD

**Issue by brandon-moy** [qnpham/week-planner#1]
## 💰 Motivation

Users will want to add items to their schedules.

## 📐 Plan

Create a button that will open up a modal to input schedule information.

## ✅ Task List

- [x] Add a button to the HTML document
- [x] The button should open up a modal with schedule information.
  - [x] The users can select the day of week, time, and description of event.
- [x] The user can submit to save the entry.
- [x] There should be a data model to store the schedule information
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
