### ISSUE TITLE
Issue 2: Users should be able to view an entry

### ISSUE THREAD

**Issue by brandon-moy** [qnpham/week-planner#2]
## 💰 Motivation

Once a user records some schedule entries, they'll want to see them.

## 📐 Plan

Have displays for each date and display the scheduled information.

## ✅ Task List

- [ ] Add sibling divs for each day of the week
- [x] Add an empty table to the `div[data-view="entries"]` element in the HTML.
- [x] Add dummy data to test how the information will appear
- [x] Define a function that takes a single `entry` object and returns a table row that matches one of the example entries in the HTML.
- [x] Use a loop to create a DOM tree for each journal entry in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [x] Remove the example HTML entries once the user's entries are successfully being appended to the DOM on page load.
- [x] Add a navigation function to change views for each day.
- [ ] Ensure that submitting a new entry also creates a new row for it and adds it to the page.
- [ ] Ensure that submitting a new entry automatically shows the schedule for the day that was submitted
- [ ] Ensure that refreshing the pages shows MONDAY as its home view
- [ ] Clean up all unnecessary styling.
- [ ] Test the app some more in a private browsing tab.
- [ ] Fix all errors.
